### PR TITLE
Initial Commit: Add Existing LECSFormer Model

### PR DESCRIPTION
**Pull request by Yamini-26**
This PR includes the initial implementation of the pre-existing LECSFormer model, which can be found [here](https://github.com/ZhaoNan1/LECSFormer.git).

### CODE REVIEW

**Comment by Yamini-26** [comment]
Hi Professor @chaozheUB, I have created new PRs breaking them down into small parts as suggested. 
Also, I don't have the option to select/notify reviewers. Upon checking about it, I found that only people with write access to the repo can do that.
Screenshot 2024-12-05 092336

**Comment by chaozheUB** [comment]
This version is adding the model as it is right? If so then may be add the link to the original model in the PR description.

**Comment by Yamini-26** [comment]
> This version is adding the model as it is right? If so then may be add the link to the original model in the PR description.

Yes professor. I've linked the original code.

**Comment by chaozheUB** [comment]
Is this ready to merge then? I can approve it right away.

**Comment by chaozheUB** [comment]
@Yamini-26 can you try adding me as a reviewer?

**Comment by Yamini-26** [comment]
> @Yamini-26 can you try adding me as a reviewer?
Screenshot 2024-12-16 235956

I still don't have the option, I'm not sure why. Is it maybe because these PRs were submitted before I got the access?

**Comment by chaozheUB** [comment]
> > @Yamini-26 can you try adding me as a reviewer?
> > Screenshot 2024-12-16 235956
> 
> I still don't have the option, I'm not sure why. Is it maybe because these PRs were submitted before I got the access?

I think you need to accept the invitation to join this project as a writer. I have recent the invitation on slack channel.

**Review by chaozheUB — APPROVED** [review]

**Pull request merged**
